### ISSUE TITLE
Lock configuration settings

### ISSUE THREAD

**Issue by borisbergman** [borisbergman/EscMonitoring#64]
Password for editing settings, 
connection, email, file location, background picture, left drawing schematic, automatic email message, clear log

Hide ssl password email
1h

**Comment by RamonZwaga** [comment]
Where is PW stored?
Add backdoor PW 2673.

-Current lock locks the 'screen settings' > should stay unlocked
-Mouseover is locked ? should stay unlocked; with that the window with pictures (and additional info) should remain operating (only txt field should not be editable)
-Dropdown menu's at the left should remain operating when 'lock' is active, otherwise one can not use the additional info field, legend lsit etc.

**Comment by borisbergman** [comment]
Added SHA1 hash to password (someone might use this password elsewhere)
Added backdoor 2673
Fixed bug when pressing cntr+p same thing should happen as clicking menu option
Disabled Schematic overview locking
